### ISSUE TITLE
Multiple exporter endpoints does not work

### ISSUE THREAD

**Issue by nodiesBlade** [baaspoolsllc/nodies_monitoring#15]
* **What is the current behavior?**
Providing multiple exporter_endpoints does not result in the correct promethesus.yml file which causes scraping tasks to fail.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Use multiple exporter endpoints for any `exporter_endpoints` in `settings.yml`

* **What is the expected behavior?**
```yml
scrape_configs:
- job_name: node
  scrape_interval: 5s
  static_configs:
  - targets:
    - host 1
    - host 2
```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
This is what it looks like after running `setup.py`

```yml
scrape_configs:
- job_name: node
  scrape_interval: 5s
  static_configs:
  - targets:
    - host1,host2
```

**Comment by YuppiePF** [comment]
I am unable to reproduce this issue.
Can you post how you are listing the multiple `exporter_endpoints` in `settings.yml`?

When I use
```
  exporter_endpoints:
    cadvisor: ["111.222.333.002:8080", "111.222.333.003:8080"]
    blockchain: ["111.222.333.002:9877", "111.222.333.003:9877"]
    node: ["111.222.333.002:9100", "111.222.333.003:9100"]
```

I am seeing below in `prometheus.yml` when running `settings.yml` from staging branch.

```
scrape_configs:
- job_name: node
  scrape_interval: 5s
  static_configs:
  - targets:
    - 111.222.333.002:9100
    - 111.222.333.003:9100
- job_name: blockchain
  scrape_interval: 5s
  static_configs:
  - targets:
    - 111.222.333.002:9877
    - 111.222.333.003:9877
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - 111.222.333.002:8080
    - 111.222.333.003:8080
```
